baseURL = 'blog.zain-khan.dev'
title = "Zain's Tech Blog"
description = "Arch Linux, Custom ROMs, and Self-Hosting"
languageCode = "en-au"
theme="hello-friend-ng"

[params.logo]
  logoText = "zain-khan"      # This changes the "hello" part
  logoHomeLink = "/"          # Or "https://zain-khan.dev" to go to your portfolio

[[menu.main]]
  identifier = "posts"
  name       = "Posts"
  url        = "/posts/"
