baseURL = 'blog.zain-khan.dev'
title = "Zain's Tech Blog"
description = "Arch Linux, Custom ROMs, and Self-Hosting"
languageCode = "en-au"
theme = "PaperMod"
theme = "PaperMod"
theme = "PaperMod"
theme = "PaperMod"
