baseURL = 'blog.zain-khan.dev'
title = "Zain's Tech Blog"
description = "Arch Linux, Custom ROMs, and Self-Hosting"
languageCode = "en-au"
theme="hello-friend-ng"

[params.logo]
  logoText = "zain-khan"      
  logoHomeLink = "/"          
  
[[menu.main]]
  name = "RSS"
  url = "/index.xml"
  weight = 100
  
[[menu.main]]
  identifier = "posts"
  name       = "Posts"
  url        = "/posts/"

[[params.social]]
  name = "github"
  url = "github.com/zai1208"
[[params.social]]
  name = "twitter"
  url = "twitter.com/zai1208"
[[params.social]]
  name = "bluesky"
  url = "bsky.app/profile/zain-khan.dev"
[[params.social]]
  name = "matrix"
  url = "matrix.to/#/@zain-khan:matrix.org"
[[params.social]]
  name = "telegram"
  url = "https://t.me/zai1208"
[[params.social]]
  name = "discord"
  url = "https://discord.com/ussers/1054414892034198086"
[[params.social]]
  name = "email"
  url = "mailto:contact@zain-khan.dev"
